# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geniegui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GenieGUI(object):
    def setupUi(self, GenieGUI):
        GenieGUI.setObjectName(_fromUtf8("GenieGUI"))
        GenieGUI.setWindowModality(QtCore.Qt.NonModal)
        GenieGUI.resize(312, 590)
        GenieGUI.setMinimumSize(QtCore.QSize(312, 590))
        GenieGUI.setMaximumSize(QtCore.QSize(312, 590))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GenieGUI.setWindowIcon(icon)
        self.windowWidget = QtGui.QWidget(GenieGUI)
        self.windowWidget.setMinimumSize(QtCore.QSize(312, 590))
        self.windowWidget.setMaximumSize(QtCore.QSize(312, 590))
        self.windowWidget.setObjectName(_fromUtf8("windowWidget"))
        self.createButton = QtGui.QPushButton(self.windowWidget)
        self.createButton.setGeometry(QtCore.QRect(210, 550, 80, 21))
        self.createButton.setAutoFillBackground(False)
        self.createButton.setFlat(False)
        self.createButton.setObjectName(_fromUtf8("createButton"))
        self.solutionLineEdit = QtGui.QLineEdit(self.windowWidget)
        self.solutionLineEdit.setEnabled(True)
        self.solutionLineEdit.setGeometry(QtCore.QRect(100, 20, 161, 22))
        self.solutionLineEdit.setObjectName(_fromUtf8("solutionLineEdit"))
        self.solutionLabel = QtGui.QLabel(self.windowWidget)
        self.solutionLabel.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.solutionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.solutionLabel.setObjectName(_fromUtf8("solutionLabel"))
        self.configurationsLabel = QtGui.QLabel(self.windowWidget)
        self.configurationsLabel.setGeometry(QtCore.QRect(10, 50, 81, 20))
        self.configurationsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.configurationsLabel.setObjectName(_fromUtf8("configurationsLabel"))
        self.configurationsDebugCheckBox = QtGui.QCheckBox(self.windowWidget)
        self.configurationsDebugCheckBox.setGeometry(QtCore.QRect(100, 50, 71, 19))
        self.configurationsDebugCheckBox.setObjectName(_fromUtf8("configurationsDebugCheckBox"))
        self.configurationsReleaseCheckBox = QtGui.QCheckBox(self.windowWidget)
        self.configurationsReleaseCheckBox.setGeometry(QtCore.QRect(160, 50, 71, 19))
        self.configurationsReleaseCheckBox.setObjectName(_fromUtf8("configurationsReleaseCheckBox"))
        self.logLabel = QtGui.QLabel(self.windowWidget)
        self.logLabel.setGeometry(QtCore.QRect(20, 550, 181, 20))
        self.logLabel.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"font-style: italic;"))
        self.logLabel.setText(_fromUtf8(""))
        self.logLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.logLabel.setObjectName(_fromUtf8("logLabel"))
        self.projectLineEdit = QtGui.QLineEdit(self.windowWidget)
        self.projectLineEdit.setEnabled(True)
        self.projectLineEdit.setGeometry(QtCore.QRect(100, 110, 161, 22))
        self.projectLineEdit.setObjectName(_fromUtf8("projectLineEdit"))
        self.projectLabel = QtGui.QLabel(self.windowWidget)
        self.projectLabel.setGeometry(QtCore.QRect(10, 110, 81, 20))
        self.projectLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.projectLabel.setObjectName(_fromUtf8("projectLabel"))
        self.platformsX32CheckBox = QtGui.QCheckBox(self.windowWidget)
        self.platformsX32CheckBox.setGeometry(QtCore.QRect(100, 80, 71, 19))
        self.platformsX32CheckBox.setObjectName(_fromUtf8("platformsX32CheckBox"))
        self.platformsLabel = QtGui.QLabel(self.windowWidget)
        self.platformsLabel.setGeometry(QtCore.QRect(10, 80, 81, 20))
        self.platformsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.platformsLabel.setObjectName(_fromUtf8("platformsLabel"))
        self.platformsX64CheckBox = QtGui.QCheckBox(self.windowWidget)
        self.platformsX64CheckBox.setGeometry(QtCore.QRect(160, 80, 71, 19))
        self.platformsX64CheckBox.setObjectName(_fromUtf8("platformsX64CheckBox"))
        self.kindLabel = QtGui.QLabel(self.windowWidget)
        self.kindLabel.setGeometry(QtCore.QRect(10, 140, 81, 20))
        self.kindLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kindLabel.setObjectName(_fromUtf8("kindLabel"))
        self.kindConsoleRadioButton = QtGui.QRadioButton(self.windowWidget)
        self.kindConsoleRadioButton.setGeometry(QtCore.QRect(100, 140, 84, 19))
        self.kindConsoleRadioButton.setChecked(True)
        self.kindConsoleRadioButton.setObjectName(_fromUtf8("kindConsoleRadioButton"))
        self.kindStaticRadioButton = QtGui.QRadioButton(self.windowWidget)
        self.kindStaticRadioButton.setGeometry(QtCore.QRect(190, 140, 84, 19))
        self.kindStaticRadioButton.setObjectName(_fromUtf8("kindStaticRadioButton"))
        self.logLabelError = QtGui.QLabel(self.windowWidget)
        self.logLabelError.setGeometry(QtCore.QRect(20, 550, 181, 20))
        self.logLabelError.setStyleSheet(_fromUtf8("color: rgb(170, 0, 0);\n"
"font-style: italic;"))
        self.logLabelError.setText(_fromUtf8(""))
        self.logLabelError.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.logLabelError.setObjectName(_fromUtf8("logLabelError"))
        self.debugFrame = QtGui.QFrame(self.windowWidget)
        self.debugFrame.setEnabled(False)
        self.debugFrame.setGeometry(QtCore.QRect(10, 230, 291, 151))
        self.debugFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.debugFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.debugFrame.setObjectName(_fromUtf8("debugFrame"))
        self.debugFlagsLineEdit = QtGui.QLineEdit(self.debugFrame)
        self.debugFlagsLineEdit.setEnabled(False)
        self.debugFlagsLineEdit.setGeometry(QtCore.QRect(90, 60, 161, 22))
        self.debugFlagsLineEdit.setObjectName(_fromUtf8("debugFlagsLineEdit"))
        self.debugLinkLineEdit = QtGui.QLineEdit(self.debugFrame)
        self.debugLinkLineEdit.setEnabled(False)
        self.debugLinkLineEdit.setGeometry(QtCore.QRect(90, 90, 161, 22))
        self.debugLinkLineEdit.setDragEnabled(False)
        self.debugLinkLineEdit.setObjectName(_fromUtf8("debugLinkLineEdit"))
        self.debugFlagsLabel = QtGui.QLabel(self.debugFrame)
        self.debugFlagsLabel.setGeometry(QtCore.QRect(0, 60, 81, 20))
        self.debugFlagsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.debugFlagsLabel.setObjectName(_fromUtf8("debugFlagsLabel"))
        self.debugLinksLabel = QtGui.QLabel(self.debugFrame)
        self.debugLinksLabel.setGeometry(QtCore.QRect(0, 90, 81, 20))
        self.debugLinksLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.debugLinksLabel.setObjectName(_fromUtf8("debugLinksLabel"))
        self.debugTargetLineEdit = QtGui.QLineEdit(self.debugFrame)
        self.debugTargetLineEdit.setEnabled(False)
        self.debugTargetLineEdit.setGeometry(QtCore.QRect(90, 30, 161, 22))
        self.debugTargetLineEdit.setDragEnabled(True)
        self.debugTargetLineEdit.setReadOnly(False)
        self.debugTargetLineEdit.setObjectName(_fromUtf8("debugTargetLineEdit"))
        self.debugTargetPushButton = QtGui.QPushButton(self.debugFrame)
        self.debugTargetPushButton.setGeometry(QtCore.QRect(260, 30, 31, 21))
        self.debugTargetPushButton.setObjectName(_fromUtf8("debugTargetPushButton"))
        self.debugTargetLabel = QtGui.QLabel(self.debugFrame)
        self.debugTargetLabel.setGeometry(QtCore.QRect(0, 30, 81, 20))
        self.debugTargetLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.debugTargetLabel.setObjectName(_fromUtf8("debugTargetLabel"))
        self.debugLabel = QtGui.QLabel(self.debugFrame)
        self.debugLabel.setGeometry(QtCore.QRect(10, 0, 71, 20))
        self.debugLabel.setStyleSheet(_fromUtf8("font-weight: bold;"))
        self.debugLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.debugLabel.setObjectName(_fromUtf8("debugLabel"))
        self.debugDefinesLineEdit = QtGui.QLineEdit(self.debugFrame)
        self.debugDefinesLineEdit.setEnabled(False)
        self.debugDefinesLineEdit.setGeometry(QtCore.QRect(90, 120, 161, 22))
        self.debugDefinesLineEdit.setDragEnabled(False)
        self.debugDefinesLineEdit.setObjectName(_fromUtf8("debugDefinesLineEdit"))
        self.debugDefinesLabel = QtGui.QLabel(self.debugFrame)
        self.debugDefinesLabel.setGeometry(QtCore.QRect(0, 120, 81, 20))
        self.debugDefinesLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.debugDefinesLabel.setObjectName(_fromUtf8("debugDefinesLabel"))
        self.releaseFrame = QtGui.QFrame(self.windowWidget)
        self.releaseFrame.setEnabled(False)
        self.releaseFrame.setGeometry(QtCore.QRect(10, 390, 291, 151))
        self.releaseFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.releaseFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.releaseFrame.setObjectName(_fromUtf8("releaseFrame"))
        self.releaseFlagsLineEdit = QtGui.QLineEdit(self.releaseFrame)
        self.releaseFlagsLineEdit.setEnabled(False)
        self.releaseFlagsLineEdit.setGeometry(QtCore.QRect(90, 60, 161, 22))
        self.releaseFlagsLineEdit.setObjectName(_fromUtf8("releaseFlagsLineEdit"))
        self.releaseLinkLineEdit = QtGui.QLineEdit(self.releaseFrame)
        self.releaseLinkLineEdit.setEnabled(False)
        self.releaseLinkLineEdit.setGeometry(QtCore.QRect(90, 90, 161, 22))
        self.releaseLinkLineEdit.setObjectName(_fromUtf8("releaseLinkLineEdit"))
        self.releaseFlagsLabel = QtGui.QLabel(self.releaseFrame)
        self.releaseFlagsLabel.setGeometry(QtCore.QRect(0, 60, 81, 20))
        self.releaseFlagsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.releaseFlagsLabel.setObjectName(_fromUtf8("releaseFlagsLabel"))
        self.releaseLinksLabel = QtGui.QLabel(self.releaseFrame)
        self.releaseLinksLabel.setGeometry(QtCore.QRect(0, 90, 81, 20))
        self.releaseLinksLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.releaseLinksLabel.setObjectName(_fromUtf8("releaseLinksLabel"))
        self.releaseTargetLineEdit = QtGui.QLineEdit(self.releaseFrame)
        self.releaseTargetLineEdit.setEnabled(False)
        self.releaseTargetLineEdit.setGeometry(QtCore.QRect(90, 30, 161, 22))
        self.releaseTargetLineEdit.setDragEnabled(True)
        self.releaseTargetLineEdit.setReadOnly(False)
        self.releaseTargetLineEdit.setObjectName(_fromUtf8("releaseTargetLineEdit"))
        self.releaseTargetPushButton = QtGui.QPushButton(self.releaseFrame)
        self.releaseTargetPushButton.setGeometry(QtCore.QRect(260, 30, 31, 21))
        self.releaseTargetPushButton.setObjectName(_fromUtf8("releaseTargetPushButton"))
        self.releaseTargetLabel = QtGui.QLabel(self.releaseFrame)
        self.releaseTargetLabel.setGeometry(QtCore.QRect(0, 30, 81, 20))
        self.releaseTargetLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.releaseTargetLabel.setObjectName(_fromUtf8("releaseTargetLabel"))
        self.releaseLabel = QtGui.QLabel(self.releaseFrame)
        self.releaseLabel.setGeometry(QtCore.QRect(10, 0, 71, 20))
        self.releaseLabel.setStyleSheet(_fromUtf8("font-weight: bold;"))
        self.releaseLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.releaseLabel.setObjectName(_fromUtf8("releaseLabel"))
        self.releaseDefinesLabel = QtGui.QLabel(self.releaseFrame)
        self.releaseDefinesLabel.setGeometry(QtCore.QRect(0, 120, 81, 20))
        self.releaseDefinesLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.releaseDefinesLabel.setObjectName(_fromUtf8("releaseDefinesLabel"))
        self.releaseDefinesLineEdit = QtGui.QLineEdit(self.releaseFrame)
        self.releaseDefinesLineEdit.setEnabled(False)
        self.releaseDefinesLineEdit.setGeometry(QtCore.QRect(90, 120, 161, 22))
        self.releaseDefinesLineEdit.setObjectName(_fromUtf8("releaseDefinesLineEdit"))
        self.includeLabel = QtGui.QLabel(self.windowWidget)
        self.includeLabel.setGeometry(QtCore.QRect(10, 170, 81, 20))
        self.includeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.includeLabel.setObjectName(_fromUtf8("includeLabel"))
        self.fileLabel = QtGui.QLabel(self.windowWidget)
        self.fileLabel.setGeometry(QtCore.QRect(10, 200, 81, 20))
        self.fileLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fileLabel.setObjectName(_fromUtf8("fileLabel"))
        self.includeComboBox = QtGui.QComboBox(self.windowWidget)
        self.includeComboBox.setGeometry(QtCore.QRect(100, 170, 131, 22))
        self.includeComboBox.setObjectName(_fromUtf8("includeComboBox"))
        self.fileComboBox = QtGui.QComboBox(self.windowWidget)
        self.fileComboBox.setGeometry(QtCore.QRect(100, 200, 131, 22))
        self.fileComboBox.setObjectName(_fromUtf8("fileComboBox"))
        self.includeAddPushButton = QtGui.QPushButton(self.windowWidget)
        self.includeAddPushButton.setGeometry(QtCore.QRect(240, 170, 31, 21))
        self.includeAddPushButton.setObjectName(_fromUtf8("includeAddPushButton"))
        self.fileRemovePushButton = QtGui.QPushButton(self.windowWidget)
        self.fileRemovePushButton.setGeometry(QtCore.QRect(270, 200, 31, 21))
        self.fileRemovePushButton.setObjectName(_fromUtf8("fileRemovePushButton"))
        self.includeRemovePushButton = QtGui.QPushButton(self.windowWidget)
        self.includeRemovePushButton.setGeometry(QtCore.QRect(270, 170, 31, 21))
        self.includeRemovePushButton.setObjectName(_fromUtf8("includeRemovePushButton"))
        self.fileAddPushButton = QtGui.QPushButton(self.windowWidget)
        self.fileAddPushButton.setGeometry(QtCore.QRect(240, 200, 31, 21))
        self.fileAddPushButton.setObjectName(_fromUtf8("fileAddPushButton"))
        self.createButton.raise_()
        self.solutionLineEdit.raise_()
        self.solutionLabel.raise_()
        self.configurationsLabel.raise_()
        self.configurationsDebugCheckBox.raise_()
        self.configurationsReleaseCheckBox.raise_()
        self.logLabel.raise_()
        self.projectLineEdit.raise_()
        self.projectLabel.raise_()
        self.platformsX32CheckBox.raise_()
        self.platformsLabel.raise_()
        self.platformsX64CheckBox.raise_()
        self.kindLabel.raise_()
        self.kindConsoleRadioButton.raise_()
        self.kindStaticRadioButton.raise_()
        self.logLabelError.raise_()
        self.debugFrame.raise_()
        self.releaseFrame.raise_()
        self.includeLabel.raise_()
        self.fileLabel.raise_()
        self.includeComboBox.raise_()
        self.fileComboBox.raise_()
        self.includeAddPushButton.raise_()
        self.fileRemovePushButton.raise_()
        self.includeRemovePushButton.raise_()
        self.fileAddPushButton.raise_()
        GenieGUI.setCentralWidget(self.windowWidget)

        self.retranslateUi(GenieGUI)
        QtCore.QMetaObject.connectSlotsByName(GenieGUI)

    def retranslateUi(self, GenieGUI):
        GenieGUI.setWindowTitle(_translate("GenieGUI", "GenieGUI", None))
        self.createButton.setText(_translate("GenieGUI", "Create File", None))
        self.solutionLabel.setText(_translate("GenieGUI", "Solution Name", None))
        self.configurationsLabel.setText(_translate("GenieGUI", "Configurations", None))
        self.configurationsDebugCheckBox.setText(_translate("GenieGUI", "Debug", None))
        self.configurationsReleaseCheckBox.setText(_translate("GenieGUI", "Release", None))
        self.projectLabel.setText(_translate("GenieGUI", "Project Name", None))
        self.platformsX32CheckBox.setText(_translate("GenieGUI", "x32", None))
        self.platformsLabel.setText(_translate("GenieGUI", "Platforms", None))
        self.platformsX64CheckBox.setText(_translate("GenieGUI", "x64", None))
        self.kindLabel.setText(_translate("GenieGUI", "Kind", None))
        self.kindConsoleRadioButton.setText(_translate("GenieGUI", "ConsoleApp", None))
        self.kindStaticRadioButton.setText(_translate("GenieGUI", "StaticLib", None))
        self.debugFlagsLabel.setText(_translate("GenieGUI", "Flags", None))
        self.debugLinksLabel.setText(_translate("GenieGUI", "Links", None))
        self.debugTargetPushButton.setText(_translate("GenieGUI", "...", None))
        self.debugTargetLabel.setText(_translate("GenieGUI", "Target Dir", None))
        self.debugLabel.setText(_translate("GenieGUI", "Debug", None))
        self.debugDefinesLabel.setText(_translate("GenieGUI", "Defines", None))
        self.releaseFlagsLabel.setText(_translate("GenieGUI", "Flags", None))
        self.releaseLinksLabel.setText(_translate("GenieGUI", "Links", None))
        self.releaseTargetPushButton.setText(_translate("GenieGUI", "...", None))
        self.releaseTargetLabel.setText(_translate("GenieGUI", "Target Dir", None))
        self.releaseLabel.setText(_translate("GenieGUI", "Release", None))
        self.releaseDefinesLabel.setText(_translate("GenieGUI", "Defines", None))
        self.includeLabel.setText(_translate("GenieGUI", "Include Dirs", None))
        self.fileLabel.setText(_translate("GenieGUI", "Files", None))
        self.includeAddPushButton.setText(_translate("GenieGUI", "+", None))
        self.fileRemovePushButton.setText(_translate("GenieGUI", "-", None))
        self.includeRemovePushButton.setText(_translate("GenieGUI", "-", None))
        self.fileAddPushButton.setText(_translate("GenieGUI", "+", None))

